---

- hosts: all
  become: true
  tasks:

  - name: Find files to delete
    tags: del-certs
    find:
      paths: /etc/ssl/certs/
      patterns: "lab*"
      file_type: file
    register: files_to_delete

  - name: Display files to be deleted
    tags: del-certs
    debug:
      var: files_to_delete.files

  - name: Delete files
    tags: del-certs
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"

  - name: stop UFW service
    ansible.builtin.systemd:
      name: ufw
      state: stopped
      enabled: false

  - name: remove UFW package
    package:
      name: ufw
      state: absent

  - name: stop haproxy service
    tags: haproxy
    service:
      name: haproxy
      state: stopped
      enabled: no

  - name: remove HAProxy package
    tags: haproxy
    package:
      name: haproxy
      state: absent
      purge: yes

  - name: remove HAProxy from systemd
    file:
      path: /etc/systemd/system/haproxy.service
      state: absent
