---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index for Ubuntu
    tags: always
    apt:
      update_cache: yes
      changed_when: false
    when: ansible_distribution_version == "Ubuntu"

  - name: copy file
    tags: haproxycfg
    copy:
      src: haproxy.cfg
      dest: /etc/haproxy.cfg
      owner: root
      group: root
      mode: 0644

- hosts: all
  become: true
  vars:
    - server_hostname: www.lab.com
    - key_size: 4096
    - passphrase: 123
    - key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: US
    - email_address: [a@a.com]
    - organization_name: IT
  tasks:
    - name: Generate an OpenSSL private key
      community.crypto.openssl_privatekey:
        path: "/etc/ssl/certs/{{ server_hostname }}_privkey.pem"
        mode: 0644
        owner: root
        group: root
        size: "{{ key_size }}"
        type: "{{ key_type }}"
        backup: yes

    - name: Generate an OpenSSL Certificate Signing Request with Subject www.lab.com
      community.crypto.openssl_csr:
        path: "/etc/ssl/certs/{{ server_hostname }}.csr"
        mode: 0644
        owner: root
        group: root
        privatekey_path: "/etc/ssl/certs/{{ server_hostname }}_privkey.pem"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ email_address }}"
        common_name: "{{ server_hostname }}"

    - name: Generate a Self Signed OpenSSL certificate
      community.crypto.x509_certificate:
        path: "/etc/ssl/certs/{{ server_hostname }}_cert.pem"
        mode: 0644
        owner: root
        group: root
        privatekey_path: "/etc/ssl/certs/{{ server_hostname }}_privkey.pem"
        csr_path: "/etc/ssl/certs/{{ server_hostname }}.csr"
        provider: selfsigned
        owner: root
        group: root
        mode: 0644
